<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LD-4V2P3G2" name="Default test" tests="11" failures="3" timestamp="8 Mar 2018 21:59:26 GMT" time="3738.59" errors="0">
  <testcase name="testConsultantAdhocOrderDetailsOnOrderCards_2848q" time="283.341" classname="com.rf.test.website.LSD.LSDOrdersTests"/>
  <testcase name="testLoadingOrdersScreen_2821q_2820q" time="237.123" classname="com.rf.test.website.LSD.LSDOrdersTests"/>
  <testcase name="testOrderStatusOrderResultsBasedOnOrderFilter_2835q" time="314.617" classname="com.rf.test.website.LSD.LSDOrdersTests"/>
  <testcase name="testOrderTypeOrderResultsBasedOnOrderFilter_2834q" time="271.816" classname="com.rf.test.website.LSD.LSDOrdersTests"/>
  <testcase name="testPCAdhocOrderDetailsOnOrderCards_2844q" time="268.617" classname="com.rf.test.website.LSD.LSDOrdersTests"/>
  <testcase name="testPulseSubscriptionOrderDetailsOnOrderCards_2843q" time="268.982" classname="com.rf.test.website.LSD.LSDOrdersTests">
    <failure type="java.lang.AssertionError" message="1.Expected order type is personal but actual on UI Consultant Order
">
      <![CDATA[java.lang.AssertionError: 1.Expected order type is personal but actual on UI Consultant Order

	at com.rf.core.utils.SoftAssert.assertAll(SoftAssert.java:56)
	at com.rf.test.website.LSD.LSDOrdersTests.testPulseSubscriptionOrderDetailsOnOrderCards_2843q(LSDOrdersTests.java:322)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testPulseSubscriptionOrderDetailsOnOrderCards_2843q -->
  <testcase name="testRetailAdhocOrderDetailsOnOrderCards_2841q" time="236.774" classname="com.rf.test.website.LSD.LSDOrdersTests"/>
  <testcase name="testVerifyCRPOrderDetailsOnOrderCards_2838q" time="268.431" classname="com.rf.test.website.LSD.LSDOrdersTests">
    <failure type="java.lang.AssertionError" message="1.Expected order type is personal but actual on UI Consultant Order
">
      <![CDATA[java.lang.AssertionError: 1.Expected order type is personal but actual on UI Consultant Order

	at com.rf.core.utils.SoftAssert.assertAll(SoftAssert.java:56)
	at com.rf.test.website.LSD.LSDOrdersTests.testVerifyCRPOrderDetailsOnOrderCards_2838q(LSDOrdersTests.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testVerifyCRPOrderDetailsOnOrderCards_2838q -->
  <testcase name="testVerifyCRPOrderDetailsWithConsultantPersonalOnOrderCards_2855q" time="235.276" classname="com.rf.test.website.LSD.LSDOrdersTests"/>
  <testcase name="testVerifyOrderReceiptForFailedPCOrders_3430q" time="263.96" classname="com.rf.test.website.LSD.LSDOrdersTests"/>
  <testcase name="testVerifyOrderReceiptForProcessedPersonalAdhocOrders_3425q" time="368.69" classname="com.rf.test.website.LSD.LSDOrdersTests">
    <failure type="java.lang.AssertionError" message="1.View receipt link is not visible for personal processed orders
">
      <![CDATA[java.lang.AssertionError: 1.View receipt link is not visible for personal processed orders

	at com.rf.core.utils.SoftAssert.assertAll(SoftAssert.java:56)
	at com.rf.test.website.LSD.LSDOrdersTests.testVerifyOrderReceiptForProcessedPersonalAdhocOrders_3425q(LSDOrdersTests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testVerifyOrderReceiptForProcessedPersonalAdhocOrders_3425q -->
</testsuite> <!-- Default test -->
